apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pub-server
  name: pub-server
  namespace: proyecto-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub-server
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: pub-server
    spec:
      containers:
      - image: alexmaest/pubserver
        imagePullPolicy: Always
        name: pub-server
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pub-server
  name: pub-server
  namespace: proyecto-namespace
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: pub-server