apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpcserver
  name: grpcserver
  namespace: proyecto-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcserver
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: grpcserver
    spec:
      containers:
      - image: alexmaest/grpcserver
        imagePullPolicy: Always
        name: grpcserver
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpcserver
  name: grpcserver
  namespace: proyecto-namespace
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 50051
      targetPort: 50051
  selector:
    app: grpcserver