FROM golang:alpine

WORKDIR /backend

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

#RUN go build -v -o /usr/local/bin/app ./...
RUN go build -o main .

EXPOSE 6379
EXPOSE 3306

CMD ["./main"]