apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpcclient
  name: grpcclient
  namespace: proyecto-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcclient
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: grpcclient
    spec:
      containers:
      - image: alexmaest/grpcclient
        imagePullPolicy: Always
        name: grpcclient
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpcclient
  name: grpcclient
  namespace: proyecto-namespace
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: grpcclient