version: '3.8'
services:
  api: 
    build: ./api
    restart: always
    container_name: api
    stdin_open: true
    tty: true
    ports:
      - '5000:5000'

  frontend: 
    build: ./frontend
    restart: always
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - api
    links:
      - api
