apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: proyecto-namespace
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wltd/k8s-volumes/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: proyecto-namespace
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-namespace
  name: mysql
spec:
  type: NodePort # remove if using ClusterIp
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32002
  selector:
    app: mysql
  # clusterIp: none # uncomment if using ClusterIp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: proyecto-namespace
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: pass123
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
