# Imagen base de Python
FROM python:3.9-slim

# Instala las dependencias de Locust
RUN pip3 install locust

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de locust y el archivo de tráfico al contenedor
COPY traffic.py traffic.py
COPY traffic.json traffic.json

# Expone el puerto 8089, el puerto predeterminado de Locust
EXPOSE 8089

# Ejecuta el archivo de locust con el archivo de tráfico
CMD ["locust", "-f", "traffic.py"]
